/*
* generated by Xtext
*/
package org.xrepl.xscript.ui.contentassist;

import org.xrepl.xscript.ui.contentassist.AbstractXscriptProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XscriptProposalProvider extends AbstractXscriptProposalProvider {

}
