/*
* generated by Xtext
*/
package org.xrepl.xscript.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XscriptAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xrepl/xscript/parser/antlr/internal/InternalXscript.tokens");
	}
}
