/*
* generated by Xtext
*/
package org.xrepl.xscript.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xrepl.xscript.services.XscriptGrammarAccess;

public class XscriptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XscriptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xrepl.xscript.parser.antlr.internal.InternalXscriptParser createParser(XtextTokenStream stream) {
		return new org.xrepl.xscript.parser.antlr.internal.InternalXscriptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "XScript";
	}
	
	public XscriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XscriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
